//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWeb22.Infraestucture.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Trabajo = new HashSet<Trabajo>();
        }
    
        public int IdCliente { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public string Direccion { get; set; }
        public string TrabajoHabitual { get; set; }
        public string Comentarios { get; set; }
        public string Cuit { get; set; }
        public string Trabajos { get; set; }
    
        public virtual ICollection<Trabajo> Trabajo { get; set; }
    }
}
