//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWeb22.Infraestucture.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajo
    {
        public int IdTrabajo { get; set; }
        public string Fecha { get; set; }
        public string Precio { get; set; }
        public string Tipo { get; set; }
        public int ClienteIdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
